# Generated by Django 4.2.9 on 2024-04-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.CharField(max_length=500)),
                ('certifications', models.CharField(blank=True, max_length=500)),
                ('interests', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
