# Generated by Django 4.2.9 on 2024-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='kur'),
            preserve_default=False,
        ),
    ]
