# Generated by Django 4.2.9 on 2024-08-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_skills_delete_skill_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(max_length=300),
        ),
    ]
