# Generated by Django 4.2.9 on 2024-08-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.CharField(max_length=300),
        ),
    ]
