# Generated by Django 4.2.9 on 2024-08-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
    ]
