# Generated by Django 4.2.9 on 2024-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
