# Generated by Django 4.2.9 on 2024-06-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('salary_range', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
