# Generated by Django 4.2.9 on 2024-08-24 10:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_joblisting_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
