# Generated by Django 4.2.9 on 2024-08-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image.png', upload_to='profile_images'),
        ),
    ]
