# Generated by Django 4.2.9 on 2024-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/')),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
