# Generated by Django 4.2.9 on 2024-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
